import type {
  ActivityRecord,
  CapabilityStatus,
  RecentPlay,
  SourceRecord,
} from "@/types/moseek";

export const initialSources: SourceRecord[] = [
  {
    key: "clzy",
    name: "初恋资源",
    sourceType: "cms",
    api: "https://api.chulian.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，支持搜索、分类、详情和播放地址。",
    enabled: true,
    lastCheckedAt: "刚刚",
    requestCount: 1284,
  },
  {
    key: "ikunzy",
    name: "ikunzy",
    sourceType: "cms",
    api: "https://ikunzy.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，字段映射完整。",
    enabled: true,
    lastCheckedAt: "2 分钟前",
    requestCount: 923,
  },
  {
    key: "豪华资源",
    name: "豪华资源",
    sourceType: "cms",
    api: "https://haohua.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，支持分页和线路切换。",
    enabled: true,
    lastCheckedAt: "5 分钟前",
    requestCount: 768,
  },
  {
    key: "hnzy",
    name: "hnzy",
    sourceType: "cms",
    api: "https://hnzy.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，响应稳定。",
    enabled: true,
    lastCheckedAt: "8 分钟前",
    requestCount: 618,
  },
  {
    key: "gszy",
    name: "gszy",
    sourceType: "cms",
    api: "https://gszy.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，支持分类筛选。",
    enabled: true,
    lastCheckedAt: "12 分钟前",
    requestCount: 542,
  },
  {
    key: "lzzy",
    name: "lzzy",
    sourceType: "cms",
    api: "https://lzzy.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，支持多线路播放。",
    enabled: true,
    lastCheckedAt: "16 分钟前",
    requestCount: 421,
  },
  {
    key: "snzy",
    name: "snzy",
    sourceType: "cms",
    api: "https://snzy.example/api.php/provide/vod",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "普通 CMS API，支持选集和详情。",
    enabled: true,
    lastCheckedAt: "21 分钟前",
    requestCount: 369,
  },
  {
    key: "xiaohu",
    name: "小胡",
    sourceType: "cms",
    api: "https://xiaohu.example/api.php/provide/vod",
    jar: "https://cdn.example.com/adapters/xiaohu.jar",
    searchable: true,
    filterable: true,
    capability: "partial",
    capabilityNote: "API 部分可用；存在远程 JAR 依赖，Moseek 不会执行。",
    enabled: true,
    lastCheckedAt: "28 分钟前",
    requestCount: 201,
  },
  {
    key: "xiongzhang",
    name: "熊掌",
    sourceType: "cms",
    api: "https://xiongzhang.example/api.php/provide/vod",
    jar: "https://cdn.example.com/adapters/xiongzhang.jar",
    searchable: true,
    filterable: false,
    capability: "partial",
    capabilityNote: "仅尝试 API 能力；远程 JAR 依赖已阻止。",
    enabled: false,
    lastCheckedAt: "31 分钟前",
    requestCount: 86,
  },
  {
    key: "live-main",
    name: "本地直播汇总",
    sourceType: "live",
    api: "https://live.example.com/channels.m3u",
    ext: "m3u",
    searchable: true,
    filterable: true,
    capability: "supported",
    capabilityNote: "M3U 直播源，可解析分组、台标和频道地址。",
    enabled: true,
    lastCheckedAt: "42 分钟前",
    requestCount: 147,
  },
  {
    key: "proxy-parser",
    name: "聚合解析接口",
    sourceType: "parser",
    api: "proxy://parse.example.com/v1",
    searchable: false,
    filterable: false,
    capability: "needs-adapter",
    capabilityNote: "TVBox 私有 proxy 协议，需要单独适配器，当前不执行。",
    enabled: false,
    lastCheckedAt: "昨天",
    requestCount: 0,
  },
  {
    key: "drpy-main",
    name: "Drpy 扩展",
    sourceType: "parser",
    api: "https://example.com/drpy.js",
    searchable: false,
    filterable: false,
    capability: "blocked",
    capabilityNote: "远程 JS 扩展默认阻止，不使用 eval 或沙箱外执行。",
    enabled: false,
    lastCheckedAt: "昨天",
    requestCount: 0,
  },
];

export const recentPlays: RecentPlay[] = [
  {
    title: "繁花",
    source: "初恋资源 · 线路 2",
    progress: 68,
    duration: "第 18 集 · 36:42",
    poster:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=480&q=80",
    updatedAt: "12 分钟前",
  },
  {
    title: "海边的曼彻斯特",
    source: "豪华资源 · 高清",
    progress: 34,
    duration: "01:02:18 / 01:57:00",
    poster:
      "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=480&q=80",
    updatedAt: "昨天",
  },
  {
    title: "人生切割术",
    source: "ikunzy · 线路 1",
    progress: 12,
    duration: "第 2 集 · 08:11",
    poster:
      "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=480&q=80",
    updatedAt: "周一",
  },
];

export const recentActivity: ActivityRecord[] = [
  {
    id: "activity-1",
    action: "导入配置",
    target: "4k.json",
    detail: "12 个源 · 7 个可用",
    status: "success",
    time: "今天 09:42",
  },
  {
    id: "activity-2",
    action: "请求失败",
    target: "熊掌 / detail",
    detail: "远程 JAR 依赖已阻止",
    status: "warning",
    time: "今天 09:38",
  },
  {
    id: "activity-3",
    action: "播放完成",
    target: "繁花 · 第 17 集",
    detail: "初恋资源 · 线路 2",
    status: "success",
    time: "昨天 23:16",
  },
  {
    id: "activity-4",
    action: "解析失败",
    target: "聚合解析接口",
    detail: "proxy:// 协议暂不支持",
    status: "error",
    time: "昨天 21:05",
  },
];

export function getCapabilityCounts(sources: SourceRecord[]) {
  return sources.reduce<Record<CapabilityStatus, number>>(
    (counts, source) => {
      counts[source.capability] += 1;
      return counts;
    },
    {
      supported: 0,
      partial: 0,
      "needs-adapter": 0,
      blocked: 0,
      invalid: 0,
    },
  );
}
